# Generated by Django 6.0.5 on 2026-05-13 10:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('rent', 'Rent & Office'), ('salaries', 'Salaries & Wages'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('travel', 'Travel & Entertainment'), ('professional', 'Professional Services'), ('technology', 'Technology & Software'), ('bank_charges', 'Bank Charges'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_vat_recoverable', models.BooleanField(default=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('receipt_url', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_trn', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('bank_details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'invoice_line_items',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('expense', 'Expense'), ('payment', 'Payment'), ('vat', 'VAT'), ('ct', 'Corporate Tax'), ('payroll', 'Payroll')], default='manual', max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
            ],
            options={
                'db_table': 'journal_lines',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit (Incoming)'), ('debit', 'Debit (Outgoing)'), ('internal', 'Internal Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('amount_aed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Card'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('flagged', 'Flagged for Review')], default='completed', max_length=20)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_account', models.CharField(blank=True, max_length=100)),
                ('counterparty_bank', models.CharField(blank=True, max_length=200)),
                ('counterparty_country', models.CharField(blank=True, max_length=3)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('txn_date', models.DateTimeField(db_index=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('rules_triggered', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-txn_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account')),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
    ]
