# Generated by Django 6.0.5 on 2026-05-13 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMLAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('sanctions_match', 'Sanctions Match'), ('pep_identified', 'PEP Identified'), ('adverse_media', 'Adverse Media'), ('high_risk_txn', 'High-Risk Transaction'), ('structuring', 'Potential Structuring'), ('velocity', 'Velocity Alert'), ('threshold', 'Threshold Breach'), ('geographic', 'Geographic Anomaly'), ('manual', 'Manually Created')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('escalated', 'Escalated'), ('closed_false_positive', 'Closed — False Positive'), ('closed_sar', 'Closed — SAR Filed'), ('closed_resolved', 'Closed — Resolved')], default='open', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_triggered', models.CharField(blank=True, max_length=50)),
                ('match_details', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('sar_reference', models.CharField(blank=True, help_text='CBUAE STR reference number if filed.', max_length=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aml_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMLScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening_type', models.CharField(choices=[('sanctions', 'Sanctions Screening'), ('pep', 'PEP Screening'), ('adverse_media', 'Adverse Media'), ('full', 'Full Screening (All)')], default='full', max_length=20)),
                ('result', models.CharField(choices=[('clear', 'Clear'), ('potential_match', 'Potential Match'), ('match', 'Match'), ('error', 'Error')], max_length=20)),
                ('match_score', models.FloatField(default=0.0)),
                ('sanctions_result', models.CharField(blank=True, max_length=20)),
                ('pep_result', models.CharField(blank=True, max_length=20)),
                ('adverse_media_result', models.CharField(blank=True, max_length=20)),
                ('matched_lists', models.JSONField(default=list)),
                ('matched_entries', models.JSONField(default=list)),
                ('risk_factors', models.JSONField(default=list)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'aml_screenings',
                'ordering': ['-screened_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(choices=[('R001', 'Cash Reporting Threshold (AED 55,000)'), ('R002', 'Structuring Detection (< 24h aggregate)'), ('R003', 'Round Number Transactions'), ('R004', 'FATF Grey/Black List Country'), ('R005', 'High-Risk Customer Transaction'), ('R006', 'High Velocity (> 10 txns/hour)'), ('R007', 'Geographic Anomaly'), ('R008', 'Large Cash Withdrawal'), ('CUSTOM', 'Custom Rule')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('threshold_count', models.PositiveIntegerField(blank=True, null=True)),
                ('window_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Rule-specific parameters as JSON.')),
            ],
            options={
                'db_table': 'transaction_rules',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('ofac_sdn', 'OFAC SDN List'), ('un_consolidated', 'UN Consolidated List'), ('eu_consolidated', 'EU Consolidated List'), ('hm_treasury', 'HM Treasury (UK)'), ('uae_local_terrorist', 'UAE Local Terrorist List'), ('custom', 'Custom Watchlist')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False, help_text='Global lists apply to all tenants.')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('update_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'watchlists',
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('aliases', models.JSONField(default=list)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('vessel', 'Vessel'), ('aircraft', 'Aircraft')], default='individual', max_length=20)),
                ('dob', models.CharField(blank=True, max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=5)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'watchlist_entries',
            },
        ),
    ]
