# Generated by Django 6.0.5 on 2026-05-13 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('aml', '0001_initial'),
        ('kyc', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amlalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amlalert',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to='kyc.customer'),
        ),
        migrations.AddField(
            model_name='amlalert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='amlalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amlalert',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='amlscreening',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='kyc.customer'),
        ),
        migrations.AddField(
            model_name='amlscreening',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='amlscreening',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amlalert',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aml.amlscreening'),
        ),
        migrations.AddField(
            model_name='transactionrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='aml.watchlist'),
        ),
        migrations.AddIndex(
            model_name='amlalert',
            index=models.Index(fields=['organization', 'status', 'severity'], name='aml_alerts_organiz_0151dd_idx'),
        ),
        migrations.AddIndex(
            model_name='amlalert',
            index=models.Index(fields=['organization', 'created_at'], name='aml_alerts_organiz_e45cd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionrule',
            unique_together={('organization', 'rule_code')},
        ),
        migrations.AddIndex(
            model_name='watchlistentry',
            index=models.Index(fields=['watchlist', 'entity_type'], name='watchlist_e_watchli_c957cf_idx'),
        ),
    ]
