# Generated by Django 6.0.5 on 2026-05-13 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTaxReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_year', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('amended', 'Amended')], default='draft', max_length=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accounting_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('add_back_disallowable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('less_exempt_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exemption_threshold', models.DecimalField(decimal_places=2, default=375000, max_digits=18)),
                ('taxable_income_above_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ct_rate', models.DecimalField(decimal_places=4, default='0.09', max_digits=5)),
                ('ct_liability', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('effective_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('small_business_relief', models.BooleanField(default=False)),
                ('filing_deadline', models.DateField()),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('mof_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ct_returns',
                'ordering': ['-tax_year'],
            },
        ),
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('amended', 'Amended')], default='draft', max_length=10)),
                ('standard_rated_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('zero_rated_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exempt_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('standard_rated_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('recoverable_input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('non_recoverable_input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_refund', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('fta_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'vat_returns',
                'ordering': ['-period_start'],
            },
        ),
    ]
