# Generated by Django 6.0.5 on 2026-05-13 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetaxreturn',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporatetaxreturn',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatetaxreturn',
            unique_together={('organization', 'tax_year')},
        ),
        migrations.AlterUniqueTogether(
            name='vatreturn',
            unique_together={('organization', 'period_start', 'period_end')},
        ),
    ]
