# Generated by Django 6.0.5 on 2026-05-13 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('emirates_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('emirates_id_expiry', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_status', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('trade_license_no', models.CharField(blank=True, max_length=50)),
                ('trade_license_expiry', models.DateField(blank=True, null=True)),
                ('business_activity', models.CharField(blank=True, max_length=255)),
                ('incorporation_country', models.CharField(blank=True, max_length=3)),
                ('trn', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emirate', models.CharField(blank=True, max_length=30)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('kyc_expiry_date', models.DateField(blank=True, null=True)),
                ('is_pep', models.BooleanField(default=False)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('pep_detail', models.TextField(blank=True)),
                ('requires_edd', models.BooleanField(default=False)),
                ('edd_notes', models.TextField(blank=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=100)),
                ('source_of_wealth', models.CharField(blank=True, max_length=100)),
                ('expected_annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('last_screened_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('emirates_id_front', 'Emirates ID (Front)'), ('emirates_id_back', 'Emirates ID (Back)'), ('passport', 'Passport'), ('visa', 'Visa Copy'), ('trade_license', 'Trade License'), ('moa', 'Memorandum of Association'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill (Proof of Address)'), ('financial_statement', 'Financial Statement'), ('other', 'Other')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='UBODeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_pep', models.BooleanField(default=False)),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('screening_result', models.CharField(blank=True, choices=[('clear', 'Clear'), ('match', 'Match'), ('potential_match', 'Potential Match')], max_length=20)),
            ],
            options={
                'db_table': 'ubo_declarations',
            },
        ),
    ]
