# Generated by Django 6.0.5 on 2026-05-13 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('trade_license_no', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('bank', 'Bank'), ('exchange', 'Exchange House'), ('broker', 'Broker'), ('accounting', 'Accounting Firm'), ('trading', 'Trading Company'), ('fintech', 'FinTech'), ('other', 'Other')], default='other', max_length=30)),
                ('trn', models.CharField(blank=True, help_text='UAE Tax Registration Number (15 digits)', max_length=20)),
                ('cbuae_license_no', models.CharField(blank=True, help_text='CBUAE regulated entity license', max_length=50)),
                ('emirate', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('compliance_email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_count_this_month', models.PositiveIntegerField(default=0)),
                ('api_calls_this_month', models.PositiveIntegerField(default=0)),
                ('screening_count_this_month', models.PositiveIntegerField(default=0)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=64)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=50)),
                ('currency', models.CharField(default='AED', max_length=3)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
    ]
