# Generated by Django 6.0.5 on 2026-05-13 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('sar_summary', 'SAR Summary'), ('screening_summary', 'Screening Summary'), ('transaction_monitoring', 'Transaction Monitoring'), ('kyc_status', 'KYC Status Report'), ('vat_return', 'VAT Return (VAT-201)'), ('corporate_tax', 'Corporate Tax Return'), ('trial_balance', 'Trial Balance'), ('income_statement', 'Income Statement (P&L)'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('params', models.JSONField(default=dict)),
                ('file_url', models.TextField(blank=True)),
                ('blob_name', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization')),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
